# Generated by Django 6.0.1 on 2026-01-09 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Color en formato hexadecimal (ej: #3B82F6)', max_length=7)),
                ('icono', models.CharField(default='calendar', help_text='Nombre del ícono para el frontend', max_length=50)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(db_index=True)),
                ('fecha_fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('todo_el_dia', models.BooleanField(default=False, help_text='Si es True, el evento dura todo el día')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_recurrencia', models.CharField(choices=[('NINGUNA', 'Sin recurrencia'), ('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], db_index=True, default='NINGUNA', max_length=20)),
                ('fecha_fin_recurrencia', models.DateTimeField(blank=True, help_text='Fecha hasta la cual se repite el evento', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('recordatorio_minutos', models.IntegerField(blank=True, help_text='Minutos antes del evento para enviar recordatorio (ej: 30, 60, 1440)', null=True)),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Usuario asignado al evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario que creó el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='calendario.tipoevento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('enviado', models.BooleanField(default=False)),
                ('metodo', models.CharField(default='SISTEMA', help_text='Método de envío: SISTEMA, EMAIL, SMS, etc.', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='calendario.evento')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['evento', '-fecha_envio'], name='calendario__evento__f6b24f_idx'), models.Index(fields=['enviado'], name='calendario__enviado_fdf334_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tipoevento',
            index=models.Index(fields=['nombre'], name='calendario__nombre_7d492e_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_inicio', 'estado'], name='calendario__fecha_i_a44c33_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo', 'fecha_inicio'], name='calendario__tipo_id_836618_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['asignado_a', 'fecha_inicio'], name='calendario__asignad_8204b0_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['estado'], name='calendario__estado_fdafe9_idx'),
        ),
    ]
