# Generated by Django 6.0.1 on 2026-01-09 04:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galpon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('capacidad_maxima', models.IntegerField(help_text='Capacidad máxima de aves en el galpón', validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si el galpón está en uso')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Galpón',
                'verbose_name_plural': 'Galpones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('fecha_ingreso', models.DateField(db_index=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('cantidad_aves', models.IntegerField(help_text='Cantidad inicial de aves en el lote', validators=[django.core.validators.MinValueValidator(1)])),
                ('raza', models.CharField(blank=True, help_text='Raza de las gallinas (ej: Lohmann Brown, Hy-Line)', max_length=100)),
                ('estado', models.CharField(choices=[('CRECIMIENTO', 'Crecimiento'), ('PRODUCCION', 'En Producción'), ('MUDAS', 'En Mudas'), ('FINALIZADO', 'Finalizado')], db_index=True, default='CRECIMIENTO', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si el lote está activo')),
                ('notas', models.TextField(blank=True, null=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('galpon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='produccion.galpon')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(db_index=True)),
                ('cantidad_huevos', models.IntegerField(help_text='Cantidad de huevos recolectados', validators=[django.core.validators.MinValueValidator(0)])),
                ('hora_recoleccion', models.TimeField(blank=True, help_text='Hora aproximada de recolección', null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolecciones', to='produccion.lote')),
                ('recolectado_por', models.ForeignKey(help_text='Usuario que registró la recolección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recolecciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recolección',
                'verbose_name_plural': 'Recolecciones',
                'ordering': ['-fecha', '-hora_recoleccion'],
            },
        ),
        migrations.CreateModel(
            name='CalidadHuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('cantidad_primera', models.IntegerField(default=0, help_text='Cantidad de huevos de primera calidad', validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_segunda', models.IntegerField(default=0, help_text='Cantidad de huevos de segunda calidad', validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_descarte', models.IntegerField(default=0, help_text='Cantidad de huevos descartados', validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_defecto', models.CharField(choices=[('NINGUNO', 'Sin defectos'), ('CASCARON_DEBIL', 'Cáscara débil'), ('CASCARON_ROTO', 'Cáscara rota'), ('SUCIO', 'Huevo sucio'), ('FORMA_IRREGULAR', 'Forma irregular'), ('TAMAÑO_PEQUENO', 'Tamaño pequeño'), ('OTRO', 'Otro')], db_index=True, default='NINGUNO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('evaluado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huevos_evaluados', to=settings.AUTH_USER_MODEL)),
                ('recoleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calidad_huevos', to='produccion.recoleccion')),
            ],
            options={
                'verbose_name': 'Calidad de Huevo',
                'verbose_name_plural': 'Calidades de Huevo',
                'ordering': ['-recoleccion__fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='galpon',
            index=models.Index(fields=['activo', 'nombre'], name='produccion__activo_60db93_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['galpon', 'estado', '-fecha_ingreso'], name='produccion__galpon__a920a1_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['activo', '-fecha_ingreso'], name='produccion__activo_884702_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['estado'], name='produccion__estado_5acf45_idx'),
        ),
        migrations.AddIndex(
            model_name='recoleccion',
            index=models.Index(fields=['lote', '-fecha'], name='produccion__lote_id_073e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='recoleccion',
            index=models.Index(fields=['fecha'], name='produccion__fecha_525f09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recoleccion',
            unique_together={('lote', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='calidadhuevo',
            index=models.Index(fields=['recoleccion', 'tipo_defecto'], name='produccion__recolec_71871f_idx'),
        ),
    ]
