# Generated by Django 6.0.1 on 2026-01-09 04:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('notas_generales', models.TextField(blank=True, help_text='Notas generales sobre la salud del lote', null=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_veterinario', to='produccion.lote')),
                ('veterinario_responsable', models.ForeignKey(blank=True, help_text='Veterinario responsable del lote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_veterinario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Veterinario',
                'verbose_name_plural': 'Historiales Veterinarios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Mortalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(db_index=True)),
                ('cantidad_aves', models.IntegerField(help_text='Cantidad de aves muertas', validators=[django.core.validators.MinValueValidator(1)])),
                ('causa', models.CharField(blank=True, help_text='Causa probable de la mortalidad', max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalidades', to='produccion.lote')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortalidades_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mortalidad',
                'verbose_name_plural': 'Mortalidades',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['lote', '-fecha'], name='salud_morta_lote_id_1e7c71_idx'), models.Index(fields=['fecha'], name='salud_morta_fecha_050f0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('ANTIBIOTICO', 'Antibiótico'), ('ANTIPARASITARIO', 'Antiparasitario'), ('VITAMINAS', 'Vitaminas'), ('DESINFECTANTE', 'Desinfectante'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=20)),
                ('medicamento', models.CharField(help_text='Nombre del medicamento o tratamiento', max_length=200)),
                ('dosis', models.CharField(blank=True, help_text='Dosis aplicada (ej: 1ml por litro de agua)', max_length=100)),
                ('cantidad_aves', models.IntegerField(help_text='Cantidad de aves tratadas', validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.TextField(help_text='Motivo del tratamiento (síntomas, diagnóstico)')),
                ('resultado', models.TextField(blank=True, help_text='Resultado del tratamiento', null=True)),
                ('aplicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_aplicados', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='produccion.lote')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['lote', '-fecha_inicio'], name='salud_trata_lote_id_c4730b_idx'), models.Index(fields=['tipo', '-fecha_inicio'], name='salud_trata_tipo_5fd5ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(db_index=True)),
                ('tipo_vacuna', models.CharField(help_text='Tipo de vacuna aplicada (ej: Newcastle, Gumboro)', max_length=150)),
                ('cantidad_aves', models.IntegerField(help_text='Cantidad de aves vacunadas', validators=[django.core.validators.MinValueValidator(1)])),
                ('metodo_aplicacion', models.CharField(help_text='Método de aplicación (ej: Inyección, Agua, Spray)', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('aplicado_por', models.ForeignKey(help_text='Usuario que registró la vacunación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunaciones_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='produccion.lote')),
            ],
            options={
                'verbose_name': 'Vacunación',
                'verbose_name_plural': 'Vacunaciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['lote', '-fecha'], name='salud_vacun_lote_id_0d1a91_idx'), models.Index(fields=['fecha'], name='salud_vacun_fecha_a2d049_idx')],
            },
        ),
    ]
