# Generated by Django 6.0.1 on 2026-01-09 04:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('edad_minima_semanas', models.IntegerField(default=0, help_text='Edad mínima en semanas para usar esta fórmula', validators=[django.core.validators.MinValueValidator(0)])),
                ('edad_maxima_semanas', models.IntegerField(blank=True, help_text='Edad máxima en semanas para usar esta fórmula', null=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fórmula de Alimento',
                'verbose_name_plural': 'Fórmulas de Alimento',
                'ordering': ['edad_minima_semanas', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=150, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si el proveedor está activo')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor de Alimento',
                'verbose_name_plural': 'Proveedores de Alimento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Racion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(db_index=True)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, help_text='Cantidad de alimento en kilogramos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notas', models.TextField(blank=True, null=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raciones', to='alimentacion.formulaalimento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raciones', to='produccion.lote')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ración',
                'verbose_name_plural': 'Raciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(db_index=True)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, help_text='Cantidad consumida en kilogramos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notas', models.TextField(blank=True, null=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_diarios', to='produccion.lote')),
                ('material_alimento', models.ForeignKey(help_text='Material de alimento del inventario', limit_choices_to={'tipo_inventario': 'GRANJA'}, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_diarios', to='inventario.material')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumo Diario',
                'verbose_name_plural': 'Consumos Diarios',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['lote', '-fecha'], name='alimentacio_lote_id_8066cb_idx'), models.Index(fields=['material_alimento', '-fecha'], name='alimentacio_materia_fea0b0_idx'), models.Index(fields=['fecha'], name='alimentacio_fecha_b8b044_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='formulaalimento',
            index=models.Index(fields=['activa', 'edad_minima_semanas'], name='alimentacio_activa_1e1414_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedoralimento',
            index=models.Index(fields=['activo', 'nombre'], name='alimentacio_activo_670ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='racion',
            index=models.Index(fields=['lote', '-fecha'], name='alimentacio_lote_id_b4f4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='racion',
            index=models.Index(fields=['formula', '-fecha'], name='alimentacio_formula_02ba50_idx'),
        ),
        migrations.AddIndex(
            model_name='racion',
            index=models.Index(fields=['fecha'], name='alimentacio_fecha_19dfcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='racion',
            unique_together={('lote', 'fecha')},
        ),
    ]
