# Generated by Django 6.0.1 on 2026-01-09 04:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums_creados', to=settings.AUTH_USER_MODEL)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CarpetaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='folder', help_text='Nombre del ícono para el frontend', max_length=50)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carpeta de Documentos',
                'verbose_name_plural': 'Carpetas de Documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('PLAN_PAGO', 'Plan de Pago'), ('CONTRATO', 'Contrato'), ('COMPROBANTE_BANCO', 'Comprobante Bancario'), ('FACTURA', 'Factura'), ('PERMISO', 'Permiso Municipal'), ('PLANO', 'Plano/Diseño'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=20)),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_documento', models.DateField(db_index=True, help_text='Fecha del documento (no de subida)')),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='finanzas.carpetadocumento')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_documento'],
            },
        ),
        migrations.CreateModel(
            name='FotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='galeria/%Y/%m/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_foto', models.DateField(blank=True, db_index=True, help_text='Fecha en que se tomó la foto', null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='finanzas.album')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField(db_index=True)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('QR', 'Pago QR')], db_index=True, default='TRANSFERENCIA', max_length=20)),
                ('nro_referencia', models.CharField(blank=True, help_text='Nro de transferencia o factura', max_length=100)),
                ('es_retroactivo', models.BooleanField(default=False, help_text='Indica si el gasto se registró después de su fecha real')),
                ('notas_contexto', models.TextField(blank=True, help_text="Contexto adicional del gasto. Ej: 'Comprobante de retiro bancario, usado para mano de obra de cimientos'")),
                ('imagen_comprobante', models.ImageField(blank=True, help_text='Foto de la factura o comprobante del gasto', null=True, upload_to='comprobantes/%Y/%m/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='finanzas.categoria')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el gasto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='comprobantes/%Y/%m/')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='finanzas.gasto')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('especialidad', models.CharField(help_text='Ej: Soldadura, Materiales de construcción', max_length=100)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='finanzas.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('presupuesto_objetivo', models.DecimalField(decimal_places=2, help_text='Presupuesto total del proyecto en Bs', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('descripcion', models.TextField(blank=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='finanzas.proyecto'),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('REGISTRADOR', 'Registrador'), ('VISUALIZADOR', 'Visualizador')], default='REGISTRADOR', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('parentesco', models.CharField(help_text='Relación familiar. Ej: Hermana, Cuñado, Madre', max_length=50)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si está activo puede acceder al sistema')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['usuario__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['-creado_en'], name='finanzas_al_creado__b326cf_idx'),
        ),
        migrations.AddIndex(
            model_name='carpetadocumento',
            index=models.Index(fields=['nombre'], name='finanzas_ca_nombre_1e1cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre'], name='finanzas_ca_nombre_e266a3_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['-fecha_documento'], name='finanzas_do_fecha_d_04f509_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo', '-fecha_documento'], name='finanzas_do_tipo_f9b528_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['carpeta', '-fecha_documento'], name='finanzas_do_carpeta_6536b0_idx'),
        ),
        migrations.AddIndex(
            model_name='fotoalbum',
            index=models.Index(fields=['album', '-creado_en'], name='finanzas_fo_album_i_22e481_idx'),
        ),
        migrations.AddIndex(
            model_name='fotoalbum',
            index=models.Index(fields=['fecha_foto'], name='finanzas_fo_fecha_f_f69acf_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['gasto', '-creado_en'], name='finanzas_co_gasto_i_14aa3e_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nombre'], name='finanzas_pr_nombre_e7f3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['-fecha_inicio'], name='finanzas_pr_fecha_i_45ed82_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['nombre'], name='finanzas_pr_nombre_43d22d_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['proyecto', '-fecha'], name='finanzas_ga_proyect_188d85_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['categoria', '-fecha'], name='finanzas_ga_categor_968908_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['-fecha'], name='finanzas_ga_fecha_e81160_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['metodo_pago'], name='finanzas_ga_metodo__e7ebea_idx'),
        ),
        migrations.AddIndex(
            model_name='socio',
            index=models.Index(fields=['activo'], name='finanzas_so_activo_854c7b_idx'),
        ),
    ]
