# Generated by Django 6.0.1 on 2026-01-09 04:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tipo_inventario', models.CharField(choices=[('CONSTRUCCION', 'Material de Construcción'), ('GRANJA', 'Insumo de Granja')], db_index=True, default='CONSTRUCCION', help_text='Tipo de inventario: construcción o granja', max_length=20)),
                ('unidad_medida', models.CharField(choices=[('BOLSA', 'Bolsa'), ('PIEZA', 'Pieza / Unidad'), ('METRO_CUBICO', 'Metro Cúbico'), ('KILO', 'Kilogramo'), ('LITRO', 'Litro'), ('GLOBAL', 'Global')], default='BOLSA', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock_minimo_alerta', models.DecimalField(decimal_places=2, default=5, help_text='Nivel mínimo antes de alertar stock bajo', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, db_index=True, help_text='Código interno del material (opcional)', max_length=50, null=True, unique=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['tipo_inventario', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Ingreso)'), ('SALIDA', 'Salida (Uso/Consumo)'), ('AJUSTE', 'Ajuste de Inventario')], db_index=True, max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nota', models.CharField(blank=True, help_text='Ej: Para cimientos del galpón, Consumo diario, etc.', max_length=255)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(blank=True, help_text='Gasto asociado (solo para materiales de construcción)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='finanzas.gasto')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.material')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['tipo_inventario', 'nombre'], name='inventario__tipo_in_08ee8b_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['stock_actual'], name='inventario__stock_a_facdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['material', 'tipo', '-fecha'], name='inventario__materia_49a1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha'], name='inventario__fecha_f978ae_idx'),
        ),
    ]
